//go:build linux

package main

import (
	"embed"
	"fmt"
	"io/fs"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
)

//go:embed web
var webFS embed.FS

func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	execDir := getExecDir()
	ffmpeg := findFfmpeg()
	log.Printf("execDir=%s ffmpeg=%s port=%s", execDir, ffmpeg, port)

	an := NewAnalyzer(execDir, ffmpeg)
	runner := CreateMasteringRunner()
	go runner.Run()

	// Fan-out MasteringUpdate channel to per-job SSE watchers.
	go func() {
		for m := range runner.MasteringUpdate {
			watcher.dispatch(m)
		}
	}()

	startTokenGC()

	var nextID int
	var nextIDMu sync.Mutex

	webSub, _ := fs.Sub(webFS, "web")
	mux := http.NewServeMux()

	mux.HandleFunc("/api/reference", handleReference(execDir))
	mux.HandleFunc("/api/upload-chunk", handleUploadChunk())
	mux.HandleFunc("/api/analyze", handleAnalyze(an))
	mux.HandleFunc("/api/analyze-by-token/", handleAnalyzeByToken(an))
	mux.HandleFunc("/api/master", handleMaster(&runner, execDir, ffmpeg, &nextID, &nextIDMu))
	mux.HandleFunc("/api/download/", handleDownload())
	mux.HandleFunc("/api/files/", handleFiles())
	mux.HandleFunc("/api/debug", handleDebug(execDir))

	// Static assets — index.html gets window.__webServerMode injected.
	fileServer := http.FileServer(http.FS(webSub))
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		path := r.URL.Path
		if path == "/" || path == "/index.html" {
			serveIndexWithServerMode(w, r, webSub)
			return
		}
		fileServer.ServeHTTP(w, r)
	})

	log.Printf("listening on :%s", port)
	log.Fatal(http.ListenAndServe(":"+port, mux))
}

func handleDebug(execDir string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		var sb strings.Builder

		fmt.Fprintf(&sb, "=== env ===\nLD_LIBRARY_PATH=%s\nPATH=%s\n\n",
			os.Getenv("LD_LIBRARY_PATH"), os.Getenv("PATH"))

		binDir := filepath.Join(execDir, "phaselimiter/bin")
		fmt.Fprintf(&sb, "=== %s ===\n", binDir)
		entries, err := os.ReadDir(binDir)
		if err != nil {
			fmt.Fprintf(&sb, "ReadDir error: %v\n\n", err)
		} else {
			for _, e := range entries {
				info, _ := e.Info()
				size := int64(0)
				if info != nil {
					size = info.Size()
				}
				fmt.Fprintf(&sb, "  %s  %d\n", e.Name(), size)
			}
			fmt.Fprintln(&sb)
		}

		for _, name := range []string{"phase_limiter", "audio_analyzer"} {
			path := filepath.Join(binDir, name)
			cmd := exec.Command("ldd", path)
			out, err := cmd.CombinedOutput()
			fmt.Fprintf(&sb, "=== ldd %s (exit=%v) ===\n%s\n", name, err, string(out))
		}

		// Quick smoke-test: run phase_limiter with no args and capture stderr.
		phPath := filepath.Join(binDir, "phase_limiter")
		cmd := exec.Command(phPath)
		cmd.Env = os.Environ()
		out, err := cmd.CombinedOutput()
		fmt.Fprintf(&sb, "=== phase_limiter (no args, exit=%v) ===\n%s\n", err, string(out))

		// Show resource directory.
		resourceDir := filepath.Join(execDir, "phaselimiter/resource")
		fmt.Fprintf(&sb, "=== %s ===\n", resourceDir)
		if rEntries, rErr := os.ReadDir(resourceDir); rErr != nil {
			fmt.Fprintf(&sb, "ReadDir error: %v\n\n", rErr)
		} else {
			for _, e := range rEntries {
				info, _ := e.Info()
				size := int64(0)
				if info != nil {
					size = info.Size()
				}
				fmt.Fprintf(&sb, "  %s  %d  isDir=%v\n", e.Name(), size, e.IsDir())
			}
			fmt.Fprintln(&sb)
		}

		cachePath := filepath.Join(execDir, "phaselimiter/resource/sound_quality2_cache")
		if info, cErr := os.Stat(cachePath); cErr != nil {
			fmt.Fprintf(&sb, "sound_quality2_cache: %v\n\n", cErr)
		} else {
			fmt.Fprintf(&sb, "sound_quality2_cache: present (size=%d isDir=%v)\n\n", info.Size(), info.IsDir())
		}

		analysisDir := filepath.Join(execDir, "phaselimiter/resource/analysis_data")
		if aEntries, aErr := os.ReadDir(analysisDir); aErr != nil {
			fmt.Fprintf(&sb, "analysis_data: %v\n\n", aErr)
		} else {
			fmt.Fprintf(&sb, "analysis_data: %d files\n", len(aEntries))
			for i, e := range aEntries {
				if i >= 5 {
					fmt.Fprintf(&sb, "  ... (%d more)\n", len(aEntries)-5)
					break
				}
				fmt.Fprintf(&sb, "  %s\n", e.Name())
			}
			fmt.Fprintln(&sb)
		}

		// Smoke-test audio_analyzer with 1s silence generated by ffmpeg.
		silenceWav := filepath.Join(os.TempDir(), "pl_debug_silence.wav")
		ffmpegPath := findFfmpeg()
		genCmd := exec.Command(ffmpegPath, "-y", "-f", "lavfi", "-i", "anullsrc=r=44100:cl=stereo",
			"-t", "1", "-c:a", "pcm_f32le", silenceWav)
		genCmd.Env = os.Environ()
		if genOut, genErr := genCmd.CombinedOutput(); genErr != nil {
			fmt.Fprintf(&sb, "=== ffmpeg silence gen (exit=%v) ===\n%s\n", genErr, string(genOut))
		} else {
			defer os.Remove(silenceWav)
			aaPath := filepath.Join(binDir, "audio_analyzer")
			var aaStdout, aaStderr strings.Builder
			aaCmd := exec.Command(aaPath,
				"--mode", "default",
				"--input", silenceWav,
				"--sound_quality2=false",
				"--sound_quality2_cache", cachePath,
				"--analysis_data_dir", analysisDir,
				"--quick_exit", "false",
			)
			aaCmd.Env = os.Environ()
			aaCmd.Stdout = &aaStdout
			aaCmd.Stderr = &aaStderr
			aaErr := aaCmd.Run()
			jsonOut := aaStdout.String()
			if len(jsonOut) > 500 {
				jsonOut = jsonOut[:500] + "..."
			}
			fmt.Fprintf(&sb, "=== audio_analyzer smoke (exit=%v) ===\nstdout: %s\nstderr: %s\n",
				aaErr, jsonOut, tail(aaStderr.String(), 1000))
		}

		w.Write([]byte(sb.String()))
	}
}

func serveIndexWithServerMode(w http.ResponseWriter, r *http.Request, webSub fs.FS) {
	data, err := fs.ReadFile(webSub, "index.html")
	if err != nil {
		http.Error(w, "index.html not found", http.StatusInternalServerError)
		return
	}
	injected := strings.Replace(string(data),
		"</head>",
		"<script>window.__webServerMode=true;</script></head>",
		1,
	)
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(injected))
}
